version: "2.4"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      - MYSQL_DATABASE=almacen_ventas
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes           # Permite root sin contraseña
    ports:
      - "3306:3306"
    networks:
      - almacen-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
      interval: 10s
      retries: 5

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile.eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - almacen-network

  productos:
    build:
      context: ./productos
      dockerfile: Dockerfile.productos
    mem_limit: 512m
    ports:
      - "8085:8085"
    networks:
      - almacen-network
    depends_on:
      mysql:
        condition: service_healthy          # espera a que MySQL esté listo
      eureka-server:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/almacen_ventas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  ventas-service:
    build:
      context: ./ventas
      dockerfile: Dockerfile.ventas
    mem_limit: 512m
    ports:
      - "8087:8087"
    networks:
      - almacen-network
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/almacen_ventas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  carrito-compras:
    build:
      context: ./carrito-compras
      dockerfile: Dockerfile.carrito-compras
    mem_limit: 512m
    ports:
      - "8086:8086"
    networks:
      - almacen-network
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/almacen_ventas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.api-gateway
    mem_limit: 512m
    ports:
      - "801:801"
    networks:
      - almacen-network
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile.config-server
    mem_limit: 512m
    ports:
      - "8888:8888"
    networks:
      - almacen-network
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

volumes:
  mysql_data:

networks:
  almacen-network:
