version: "3.8"

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: ../Dockerfile.eureka-server

  productos:
    build:
      context: ./productos
      dockerfile: ../Dockerfile.productos

  ventas-service:
    build:
      context: ./ventas
      dockerfile: ../Dockerfile.ventas

  carrito-compras:
    build:
      context: ./carrito-compras
      dockerfile: ../Dockerfile.carrito-compras

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ../Dockerfile.api-gateway

  config-server:
    build:
      context: ./config-server
      dockerfile: ../Dockerfile.config-server

networks:
  almacen-network:
