spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 801
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
