spring:
  application:
    name: ventas
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/almacen_ventas
    username: root
    password: ""

server:
  port: 8087
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
